/**
 *
 *  SpatialRefSys.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace smarttrails
{

class SpatialRefSys
{
  public:
    struct Cols
    {
        static const std::string _srid;
        static const std::string _auth_name;
        static const std::string _auth_srid;
        static const std::string _srtext;
        static const std::string _proj4text;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit SpatialRefSys(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit SpatialRefSys(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    SpatialRefSys(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    SpatialRefSys() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column srid  */
    ///Get the value of the column srid, returns the default value if the column is null
    const int32_t &getValueOfSrid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSrid() const noexcept;
    ///Set the value of the column srid
    void setSrid(const int32_t &pSrid) noexcept;

    /**  For column auth_name  */
    ///Get the value of the column auth_name, returns the default value if the column is null
    const std::string &getValueOfAuthName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAuthName() const noexcept;
    ///Set the value of the column auth_name
    void setAuthName(const std::string &pAuthName) noexcept;
    void setAuthName(std::string &&pAuthName) noexcept;
    void setAuthNameToNull() noexcept;

    /**  For column auth_srid  */
    ///Get the value of the column auth_srid, returns the default value if the column is null
    const int32_t &getValueOfAuthSrid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getAuthSrid() const noexcept;
    ///Set the value of the column auth_srid
    void setAuthSrid(const int32_t &pAuthSrid) noexcept;
    void setAuthSridToNull() noexcept;

    /**  For column srtext  */
    ///Get the value of the column srtext, returns the default value if the column is null
    const std::string &getValueOfSrtext() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSrtext() const noexcept;
    ///Set the value of the column srtext
    void setSrtext(const std::string &pSrtext) noexcept;
    void setSrtext(std::string &&pSrtext) noexcept;
    void setSrtextToNull() noexcept;

    /**  For column proj4text  */
    ///Get the value of the column proj4text, returns the default value if the column is null
    const std::string &getValueOfProj4text() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProj4text() const noexcept;
    ///Set the value of the column proj4text
    void setProj4text(const std::string &pProj4text) noexcept;
    void setProj4text(std::string &&pProj4text) noexcept;
    void setProj4textToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 5;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<SpatialRefSys>;
    friend drogon::orm::BaseBuilder<SpatialRefSys, true, true>;
    friend drogon::orm::BaseBuilder<SpatialRefSys, true, false>;
    friend drogon::orm::BaseBuilder<SpatialRefSys, false, true>;
    friend drogon::orm::BaseBuilder<SpatialRefSys, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<SpatialRefSys>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> srid_;
    std::shared_ptr<std::string> authName_;
    std::shared_ptr<int32_t> authSrid_;
    std::shared_ptr<std::string> srtext_;
    std::shared_ptr<std::string> proj4text_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where srid = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where srid = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "srid,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "auth_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "auth_srid,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "srtext,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "proj4text,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace smarttrails
} // namespace drogon_model
