/**
 *
 *  Poi.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/Poi.h"

#include <drogon/utils/Utilities.h>

#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smarttrails;

const std::string Poi::Cols::_id            = "\"id\"";
const std::string Poi::Cols::_name          = "\"name\"";
const std::string Poi::Cols::_city          = "\"city\"";
const std::string Poi::Cols::_type_id       = "\"type_id\"";
const std::string Poi::Cols::_coordinates   = "\"coordinates\"";
const std::string Poi::Cols::_description   = "\"description\"";
const std::string Poi::Cols::_map_source_id = "\"map_source_id\"";
const std::string Poi::Cols::_created_at    = "\"created_at\"";
const std::string Poi::primaryKeyName       = "id";
const bool        Poi::hasPrimaryKey        = true;
const std::string Poi::tableName            = "\"poi\"";

const std::vector<typename Poi::MetaData> Poi::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"name", "std::string", "character varying", 100, 0, 0, 1},
    {"city", "std::string", "character varying", 100, 0, 0, 0},
    {"type_id", "int32_t", "integer", 4, 0, 0, 0},
    {"coordinates", "std::string", "USER-DEFINED", 0, 0, 0, 1},
    {"description", "std::string", "text", 0, 0, 0, 0},
    {"map_source_id", "int32_t", "integer", 4, 0, 0, 0},
    {"created_at", "::trantor::Date", "timestamp with time zone", 0, 0, 0, 0}};
const std::string& Poi::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Poi::Poi(const Row& r, const ssize_t indexOffset) noexcept
{
    if (indexOffset < 0)
    {
        if (!r["id"].isNull())
        {
            id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if (!r["name"].isNull())
        {
            name_ = std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if (!r["city"].isNull())
        {
            city_ = std::make_shared<std::string>(r["city"].as<std::string>());
        }
        if (!r["type_id"].isNull())
        {
            typeId_ = std::make_shared<int32_t>(r["type_id"].as<int32_t>());
        }
        if (!r["coordinates"].isNull())
        {
            coordinates_ = std::make_shared<std::string>(r["coordinates"].as<std::string>());
        }
        if (!r["description"].isNull())
        {
            description_ = std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if (!r["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>(r["map_source_id"].as<int32_t>());
        }
        if (!r["created_at"].isNull())
        {
            auto      timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if (offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull())
        {
            id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull())
        {
            name_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if (!r[index].isNull())
        {
            city_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull())
        {
            typeId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if (!r[index].isNull())
        {
            coordinates_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull())
        {
            description_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if (!r[index].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if (!r[index].isNull())
        {
            auto      timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Poi::Poi(const Json::Value&              pJson,
         const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            city_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            typeId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            coordinates_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull())
        {
            description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull())
        {
            mapSourceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Poi::Poi(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["name"].isNull())
        {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("city"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["city"].isNull())
        {
            city_ = std::make_shared<std::string>(pJson["city"].asString());
        }
    }
    if (pJson.isMember("type_id"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["type_id"].isNull())
        {
            typeId_ = std::make_shared<int32_t>((int32_t)pJson["type_id"].asInt64());
        }
    }
    if (pJson.isMember("coordinates"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["coordinates"].isNull())
        {
            coordinates_ = std::make_shared<std::string>(pJson["coordinates"].asString());
        }
    }
    if (pJson.isMember("description"))
    {
        dirtyFlag_[5] = true;
        if (!pJson["description"].isNull())
        {
            description_ = std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if (pJson.isMember("map_source_id"))
    {
        dirtyFlag_[6] = true;
        if (!pJson["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>((int32_t)pJson["map_source_id"].asInt64());
        }
    }
    if (pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if (!pJson["created_at"].isNull())
        {
            auto      timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Poi::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            city_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            typeId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            coordinates_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull())
        {
            description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull())
        {
            mapSourceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Poi::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["name"].isNull())
        {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("city"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["city"].isNull())
        {
            city_ = std::make_shared<std::string>(pJson["city"].asString());
        }
    }
    if (pJson.isMember("type_id"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["type_id"].isNull())
        {
            typeId_ = std::make_shared<int32_t>((int32_t)pJson["type_id"].asInt64());
        }
    }
    if (pJson.isMember("coordinates"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["coordinates"].isNull())
        {
            coordinates_ = std::make_shared<std::string>(pJson["coordinates"].asString());
        }
    }
    if (pJson.isMember("description"))
    {
        dirtyFlag_[5] = true;
        if (!pJson["description"].isNull())
        {
            description_ = std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if (pJson.isMember("map_source_id"))
    {
        dirtyFlag_[6] = true;
        if (!pJson["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>((int32_t)pJson["map_source_id"].asInt64());
        }
    }
    if (pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if (!pJson["created_at"].isNull())
        {
            auto      timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

const int32_t& Poi::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Poi::getId() const noexcept
{
    return id_;
}
void Poi::setId(const int32_t& pId) noexcept
{
    id_           = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Poi::PrimaryKeyType& Poi::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string& Poi::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if (name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Poi::getName() const noexcept
{
    return name_;
}
void Poi::setName(const std::string& pName) noexcept
{
    name_         = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Poi::setName(std::string&& pName) noexcept
{
    name_         = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string& Poi::getValueOfCity() const noexcept
{
    static const std::string defaultValue = std::string();
    if (city_)
        return *city_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Poi::getCity() const noexcept
{
    return city_;
}
void Poi::setCity(const std::string& pCity) noexcept
{
    city_         = std::make_shared<std::string>(pCity);
    dirtyFlag_[2] = true;
}
void Poi::setCity(std::string&& pCity) noexcept
{
    city_         = std::make_shared<std::string>(std::move(pCity));
    dirtyFlag_[2] = true;
}
void Poi::setCityToNull() noexcept
{
    city_.reset();
    dirtyFlag_[2] = true;
}

const int32_t& Poi::getValueOfTypeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (typeId_)
        return *typeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Poi::getTypeId() const noexcept
{
    return typeId_;
}
void Poi::setTypeId(const int32_t& pTypeId) noexcept
{
    typeId_       = std::make_shared<int32_t>(pTypeId);
    dirtyFlag_[3] = true;
}
void Poi::setTypeIdToNull() noexcept
{
    typeId_.reset();
    dirtyFlag_[3] = true;
}

const std::string& Poi::getValueOfCoordinates() const noexcept
{
    static const std::string defaultValue = std::string();
    if (coordinates_)
        return *coordinates_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Poi::getCoordinates() const noexcept
{
    return coordinates_;
}
void Poi::setCoordinates(const std::string& pCoordinates) noexcept
{
    coordinates_  = std::make_shared<std::string>(pCoordinates);
    dirtyFlag_[4] = true;
}
void Poi::setCoordinates(std::string&& pCoordinates) noexcept
{
    coordinates_  = std::make_shared<std::string>(std::move(pCoordinates));
    dirtyFlag_[4] = true;
}

const std::string& Poi::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if (description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Poi::getDescription() const noexcept
{
    return description_;
}
void Poi::setDescription(const std::string& pDescription) noexcept
{
    description_  = std::make_shared<std::string>(pDescription);
    dirtyFlag_[5] = true;
}
void Poi::setDescription(std::string&& pDescription) noexcept
{
    description_  = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[5] = true;
}
void Poi::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[5] = true;
}

const int32_t& Poi::getValueOfMapSourceId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (mapSourceId_)
        return *mapSourceId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Poi::getMapSourceId() const noexcept
{
    return mapSourceId_;
}
void Poi::setMapSourceId(const int32_t& pMapSourceId) noexcept
{
    mapSourceId_  = std::make_shared<int32_t>(pMapSourceId);
    dirtyFlag_[6] = true;
}
void Poi::setMapSourceIdToNull() noexcept
{
    mapSourceId_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date& Poi::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date>& Poi::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Poi::setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept
{
    createdAt_    = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}
void Poi::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[7] = true;
}

void Poi::updateId(const uint64_t id) {}

const std::vector<std::string>& Poi::insertColumns() noexcept
{
    static const std::vector<std::string> inCols = {
        "name", "city", "type_id", "coordinates", "description", "map_source_id", "created_at"};
    return inCols;
}

void Poi::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getCity())
        {
            binder << getValueOfCity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getTypeId())
        {
            binder << getValueOfTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getCoordinates())
        {
            binder << getValueOfCoordinates();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5])
    {
        if (getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6])
    {
        if (getMapSourceId())
        {
            binder << getValueOfMapSourceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7])
    {
        if (getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Poi::updateColumns() const
{
    std::vector<std::string> ret;
    if (dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if (dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if (dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Poi::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getCity())
        {
            binder << getValueOfCity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getTypeId())
        {
            binder << getValueOfTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getCoordinates())
        {
            binder << getValueOfCoordinates();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5])
    {
        if (getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6])
    {
        if (getMapSourceId())
        {
            binder << getValueOfMapSourceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7])
    {
        if (getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Poi::toJson() const
{
    Json::Value ret;
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getName())
    {
        ret["name"] = getValueOfName();
    }
    else
    {
        ret["name"] = Json::Value();
    }
    if (getCity())
    {
        ret["city"] = getValueOfCity();
    }
    else
    {
        ret["city"] = Json::Value();
    }
    if (getTypeId())
    {
        ret["type_id"] = getValueOfTypeId();
    }
    else
    {
        ret["type_id"] = Json::Value();
    }
    if (getCoordinates())
    {
        ret["coordinates"] = getValueOfCoordinates();
    }
    else
    {
        ret["coordinates"] = Json::Value();
    }
    if (getDescription())
    {
        ret["description"] = getValueOfDescription();
    }
    else
    {
        ret["description"] = Json::Value();
    }
    if (getMapSourceId())
    {
        ret["map_source_id"] = getValueOfMapSourceId();
    }
    else
    {
        ret["map_source_id"] = Json::Value();
    }
    if (getCreatedAt())
    {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

std::string Poi::toString() const
{
    return toJson().toStyledString();
}

Json::Value Poi::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if (pMasqueradingVector.size() == 8)
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (getId())
            {
                ret[pMasqueradingVector[0]] = getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (getName())
            {
                ret[pMasqueradingVector[1]] = getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (getCity())
            {
                ret[pMasqueradingVector[2]] = getValueOfCity();
            }
            else
            {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (getTypeId())
            {
                ret[pMasqueradingVector[3]] = getValueOfTypeId();
            }
            else
            {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (getCoordinates())
            {
                ret[pMasqueradingVector[4]] = getValueOfCoordinates();
            }
            else
            {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty())
        {
            if (getDescription())
            {
                ret[pMasqueradingVector[5]] = getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[6].empty())
        {
            if (getMapSourceId())
            {
                ret[pMasqueradingVector[6]] = getValueOfMapSourceId();
            }
            else
            {
                ret[pMasqueradingVector[6]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[7].empty())
        {
            if (getCreatedAt())
            {
                ret[pMasqueradingVector[7]] = getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getName())
    {
        ret["name"] = getValueOfName();
    }
    else
    {
        ret["name"] = Json::Value();
    }
    if (getCity())
    {
        ret["city"] = getValueOfCity();
    }
    else
    {
        ret["city"] = Json::Value();
    }
    if (getTypeId())
    {
        ret["type_id"] = getValueOfTypeId();
    }
    else
    {
        ret["type_id"] = Json::Value();
    }
    if (getCoordinates())
    {
        ret["coordinates"] = getValueOfCoordinates();
    }
    else
    {
        ret["coordinates"] = Json::Value();
    }
    if (getDescription())
    {
        ret["description"] = getValueOfDescription();
    }
    else
    {
        ret["description"] = Json::Value();
    }
    if (getMapSourceId())
    {
        ret["map_source_id"] = getValueOfMapSourceId();
    }
    else
    {
        ret["map_source_id"] = Json::Value();
    }
    if (getCreatedAt())
    {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

bool Poi::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if (pJson.isMember("name"))
    {
        if (!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err = "The name column cannot be null";
        return false;
    }
    if (pJson.isMember("city"))
    {
        if (!validJsonOfField(2, "city", pJson["city"], err, true))
            return false;
    }
    if (pJson.isMember("type_id"))
    {
        if (!validJsonOfField(3, "type_id", pJson["type_id"], err, true))
            return false;
    }
    if (pJson.isMember("coordinates"))
    {
        if (!validJsonOfField(4, "coordinates", pJson["coordinates"], err, true))
            return false;
    }
    else
    {
        err = "The coordinates column cannot be null";
        return false;
    }
    if (pJson.isMember("description"))
    {
        if (!validJsonOfField(5, "description", pJson["description"], err, true))
            return false;
    }
    if (pJson.isMember("map_source_id"))
    {
        if (!validJsonOfField(6, "map_source_id", pJson["map_source_id"], err, true))
            return false;
    }
    if (pJson.isMember("created_at"))
    {
        if (!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Poi::validateMasqueradedJsonForCreation(const Json::Value&              pJson,
                                             const std::vector<std::string>& pMasqueradingVector,
                                             std::string&                    err)
{
    if (pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (pJson.isMember(pMasqueradingVector[0]))
            {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (pJson.isMember(pMasqueradingVector[1]))
            {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (pJson.isMember(pMasqueradingVector[2]))
            {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (pJson.isMember(pMasqueradingVector[3]))
            {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (pJson.isMember(pMasqueradingVector[4]))
            {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[4] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[5].empty())
        {
            if (pJson.isMember(pMasqueradingVector[5]))
            {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[6].empty())
        {
            if (pJson.isMember(pMasqueradingVector[6]))
            {
                if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[7].empty())
        {
            if (pJson.isMember(pMasqueradingVector[7]))
            {
                if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err,
                                      true))
                    return false;
            }
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool Poi::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("name"))
    {
        if (!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if (pJson.isMember("city"))
    {
        if (!validJsonOfField(2, "city", pJson["city"], err, false))
            return false;
    }
    if (pJson.isMember("type_id"))
    {
        if (!validJsonOfField(3, "type_id", pJson["type_id"], err, false))
            return false;
    }
    if (pJson.isMember("coordinates"))
    {
        if (!validJsonOfField(4, "coordinates", pJson["coordinates"], err, false))
            return false;
    }
    if (pJson.isMember("description"))
    {
        if (!validJsonOfField(5, "description", pJson["description"], err, false))
            return false;
    }
    if (pJson.isMember("map_source_id"))
    {
        if (!validJsonOfField(6, "map_source_id", pJson["map_source_id"], err, false))
            return false;
    }
    if (pJson.isMember("created_at"))
    {
        if (!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Poi::validateMasqueradedJsonForUpdate(const Json::Value&              pJson,
                                           const std::vector<std::string>& pMasqueradingVector,
                                           std::string&                    err)
{
    if (pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
        {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
        {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
        {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
        {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
        {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
        {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
        {
            if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
        {
            if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err,
                                  false))
                return false;
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool Poi::validJsonOfField(size_t index, const std::string& fieldName, const Json::Value& pJson,
                           std::string& err, bool isForCreation)
{
    switch (index)
    {
        case 0:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (isForCreation)
            {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 100)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 100)";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 100)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 100)";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 5:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 6:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 7:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
