/**
 *
 *  Routes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/Routes.h"

#include <drogon/utils/Utilities.h>

#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smarttrails;

const std::string Routes::Cols::_id            = "\"id\"";
const std::string Routes::Cols::_user_id       = "\"user_id\"";
const std::string Routes::Cols::_preference_id = "\"preference_id\"";
const std::string Routes::Cols::_name          = "\"name\"";
const std::string Routes::Cols::_start_point   = "\"start_point\"";
const std::string Routes::Cols::_route_line    = "\"route_line\"";
const std::string Routes::Cols::_distance_km   = "\"distance_km\"";
const std::string Routes::Cols::_map_source_id = "\"map_source_id\"";
const std::string Routes::Cols::_created_at    = "\"created_at\"";
const std::string Routes::primaryKeyName       = "id";
const bool        Routes::hasPrimaryKey        = true;
const std::string Routes::tableName            = "\"routes\"";

const std::vector<typename Routes::MetaData> Routes::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"user_id", "int32_t", "integer", 4, 0, 0, 0},
    {"preference_id", "int32_t", "integer", 4, 0, 0, 0},
    {"name", "std::string", "character varying", 100, 0, 0, 1},
    {"start_point", "std::string", "USER-DEFINED", 0, 0, 0, 1},
    {"route_line", "std::string", "USER-DEFINED", 0, 0, 0, 1},
    {"distance_km", "std::string", "numeric", 0, 0, 0, 0},
    {"map_source_id", "int32_t", "integer", 4, 0, 0, 0},
    {"created_at", "::trantor::Date", "timestamp with time zone", 0, 0, 0, 0}};
const std::string& Routes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Routes::Routes(const Row& r, const ssize_t indexOffset) noexcept
{
    if (indexOffset < 0)
    {
        if (!r["id"].isNull())
        {
            id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if (!r["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if (!r["preference_id"].isNull())
        {
            preferenceId_ = std::make_shared<int32_t>(r["preference_id"].as<int32_t>());
        }
        if (!r["name"].isNull())
        {
            name_ = std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if (!r["start_point"].isNull())
        {
            startPoint_ = std::make_shared<std::string>(r["start_point"].as<std::string>());
        }
        if (!r["route_line"].isNull())
        {
            routeLine_ = std::make_shared<std::string>(r["route_line"].as<std::string>());
        }
        if (!r["distance_km"].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(r["distance_km"].as<std::string>());
        }
        if (!r["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>(r["map_source_id"].as<int32_t>());
        }
        if (!r["created_at"].isNull())
        {
            auto      timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if (offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull())
        {
            id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull())
        {
            userId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if (!r[index].isNull())
        {
            preferenceId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if (!r[index].isNull())
        {
            name_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if (!r[index].isNull())
        {
            startPoint_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull())
        {
            routeLine_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if (!r[index].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if (!r[index].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if (!r[index].isNull())
        {
            auto      timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Routes::Routes(const Json::Value&              pJson,
               const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            preferenceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            startPoint_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull())
        {
            routeLine_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull())
        {
            mapSourceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Routes::Routes(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if (pJson.isMember("preference_id"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["preference_id"].isNull())
        {
            preferenceId_ = std::make_shared<int32_t>((int32_t)pJson["preference_id"].asInt64());
        }
    }
    if (pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["name"].isNull())
        {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("start_point"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["start_point"].isNull())
        {
            startPoint_ = std::make_shared<std::string>(pJson["start_point"].asString());
        }
    }
    if (pJson.isMember("route_line"))
    {
        dirtyFlag_[5] = true;
        if (!pJson["route_line"].isNull())
        {
            routeLine_ = std::make_shared<std::string>(pJson["route_line"].asString());
        }
    }
    if (pJson.isMember("distance_km"))
    {
        dirtyFlag_[6] = true;
        if (!pJson["distance_km"].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(pJson["distance_km"].asString());
        }
    }
    if (pJson.isMember("map_source_id"))
    {
        dirtyFlag_[7] = true;
        if (!pJson["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>((int32_t)pJson["map_source_id"].asInt64());
        }
    }
    if (pJson.isMember("created_at"))
    {
        dirtyFlag_[8] = true;
        if (!pJson["created_at"].isNull())
        {
            auto      timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Routes::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            preferenceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            startPoint_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull())
        {
            routeLine_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull())
        {
            mapSourceId_ =
                std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Routes::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if (pJson.isMember("preference_id"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["preference_id"].isNull())
        {
            preferenceId_ = std::make_shared<int32_t>((int32_t)pJson["preference_id"].asInt64());
        }
    }
    if (pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["name"].isNull())
        {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("start_point"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["start_point"].isNull())
        {
            startPoint_ = std::make_shared<std::string>(pJson["start_point"].asString());
        }
    }
    if (pJson.isMember("route_line"))
    {
        dirtyFlag_[5] = true;
        if (!pJson["route_line"].isNull())
        {
            routeLine_ = std::make_shared<std::string>(pJson["route_line"].asString());
        }
    }
    if (pJson.isMember("distance_km"))
    {
        dirtyFlag_[6] = true;
        if (!pJson["distance_km"].isNull())
        {
            distanceKm_ = std::make_shared<std::string>(pJson["distance_km"].asString());
        }
    }
    if (pJson.isMember("map_source_id"))
    {
        dirtyFlag_[7] = true;
        if (!pJson["map_source_id"].isNull())
        {
            mapSourceId_ = std::make_shared<int32_t>((int32_t)pJson["map_source_id"].asInt64());
        }
    }
    if (pJson.isMember("created_at"))
    {
        dirtyFlag_[8] = true;
        if (!pJson["created_at"].isNull())
        {
            auto      timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

const int32_t& Routes::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Routes::getId() const noexcept
{
    return id_;
}
void Routes::setId(const int32_t& pId) noexcept
{
    id_           = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Routes::PrimaryKeyType& Routes::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t& Routes::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Routes::getUserId() const noexcept
{
    return userId_;
}
void Routes::setUserId(const int32_t& pUserId) noexcept
{
    userId_       = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}
void Routes::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t& Routes::getValueOfPreferenceId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (preferenceId_)
        return *preferenceId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Routes::getPreferenceId() const noexcept
{
    return preferenceId_;
}
void Routes::setPreferenceId(const int32_t& pPreferenceId) noexcept
{
    preferenceId_ = std::make_shared<int32_t>(pPreferenceId);
    dirtyFlag_[2] = true;
}
void Routes::setPreferenceIdToNull() noexcept
{
    preferenceId_.reset();
    dirtyFlag_[2] = true;
}

const std::string& Routes::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if (name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Routes::getName() const noexcept
{
    return name_;
}
void Routes::setName(const std::string& pName) noexcept
{
    name_         = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}
void Routes::setName(std::string&& pName) noexcept
{
    name_         = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

const std::string& Routes::getValueOfStartPoint() const noexcept
{
    static const std::string defaultValue = std::string();
    if (startPoint_)
        return *startPoint_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Routes::getStartPoint() const noexcept
{
    return startPoint_;
}
void Routes::setStartPoint(const std::string& pStartPoint) noexcept
{
    startPoint_   = std::make_shared<std::string>(pStartPoint);
    dirtyFlag_[4] = true;
}
void Routes::setStartPoint(std::string&& pStartPoint) noexcept
{
    startPoint_   = std::make_shared<std::string>(std::move(pStartPoint));
    dirtyFlag_[4] = true;
}

const std::string& Routes::getValueOfRouteLine() const noexcept
{
    static const std::string defaultValue = std::string();
    if (routeLine_)
        return *routeLine_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Routes::getRouteLine() const noexcept
{
    return routeLine_;
}
void Routes::setRouteLine(const std::string& pRouteLine) noexcept
{
    routeLine_    = std::make_shared<std::string>(pRouteLine);
    dirtyFlag_[5] = true;
}
void Routes::setRouteLine(std::string&& pRouteLine) noexcept
{
    routeLine_    = std::make_shared<std::string>(std::move(pRouteLine));
    dirtyFlag_[5] = true;
}

const std::string& Routes::getValueOfDistanceKm() const noexcept
{
    static const std::string defaultValue = std::string();
    if (distanceKm_)
        return *distanceKm_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Routes::getDistanceKm() const noexcept
{
    return distanceKm_;
}
void Routes::setDistanceKm(const std::string& pDistanceKm) noexcept
{
    distanceKm_   = std::make_shared<std::string>(pDistanceKm);
    dirtyFlag_[6] = true;
}
void Routes::setDistanceKm(std::string&& pDistanceKm) noexcept
{
    distanceKm_   = std::make_shared<std::string>(std::move(pDistanceKm));
    dirtyFlag_[6] = true;
}
void Routes::setDistanceKmToNull() noexcept
{
    distanceKm_.reset();
    dirtyFlag_[6] = true;
}

const int32_t& Routes::getValueOfMapSourceId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (mapSourceId_)
        return *mapSourceId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& Routes::getMapSourceId() const noexcept
{
    return mapSourceId_;
}
void Routes::setMapSourceId(const int32_t& pMapSourceId) noexcept
{
    mapSourceId_  = std::make_shared<int32_t>(pMapSourceId);
    dirtyFlag_[7] = true;
}
void Routes::setMapSourceIdToNull() noexcept
{
    mapSourceId_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date& Routes::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date>& Routes::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Routes::setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept
{
    createdAt_    = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[8] = true;
}
void Routes::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[8] = true;
}

void Routes::updateId(const uint64_t id) {}

const std::vector<std::string>& Routes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols = {"user_id",       "preference_id", "name",
                                                    "start_point",   "route_line",    "distance_km",
                                                    "map_source_id", "created_at"};
    return inCols;
}

void Routes::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getPreferenceId())
        {
            binder << getValueOfPreferenceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getStartPoint())
        {
            binder << getValueOfStartPoint();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5])
    {
        if (getRouteLine())
        {
            binder << getValueOfRouteLine();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6])
    {
        if (getDistanceKm())
        {
            binder << getValueOfDistanceKm();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7])
    {
        if (getMapSourceId())
        {
            binder << getValueOfMapSourceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8])
    {
        if (getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Routes::updateColumns() const
{
    std::vector<std::string> ret;
    if (dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if (dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if (dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if (dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Routes::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getPreferenceId())
        {
            binder << getValueOfPreferenceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getStartPoint())
        {
            binder << getValueOfStartPoint();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5])
    {
        if (getRouteLine())
        {
            binder << getValueOfRouteLine();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6])
    {
        if (getDistanceKm())
        {
            binder << getValueOfDistanceKm();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7])
    {
        if (getMapSourceId())
        {
            binder << getValueOfMapSourceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8])
    {
        if (getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Routes::toJson() const
{
    Json::Value ret;
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getUserId())
    {
        ret["user_id"] = getValueOfUserId();
    }
    else
    {
        ret["user_id"] = Json::Value();
    }
    if (getPreferenceId())
    {
        ret["preference_id"] = getValueOfPreferenceId();
    }
    else
    {
        ret["preference_id"] = Json::Value();
    }
    if (getName())
    {
        ret["name"] = getValueOfName();
    }
    else
    {
        ret["name"] = Json::Value();
    }
    if (getStartPoint())
    {
        ret["start_point"] = getValueOfStartPoint();
    }
    else
    {
        ret["start_point"] = Json::Value();
    }
    if (getRouteLine())
    {
        ret["route_line"] = getValueOfRouteLine();
    }
    else
    {
        ret["route_line"] = Json::Value();
    }
    if (getDistanceKm())
    {
        ret["distance_km"] = getValueOfDistanceKm();
    }
    else
    {
        ret["distance_km"] = Json::Value();
    }
    if (getMapSourceId())
    {
        ret["map_source_id"] = getValueOfMapSourceId();
    }
    else
    {
        ret["map_source_id"] = Json::Value();
    }
    if (getCreatedAt())
    {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

std::string Routes::toString() const
{
    return toJson().toStyledString();
}

Json::Value Routes::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if (pMasqueradingVector.size() == 9)
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (getId())
            {
                ret[pMasqueradingVector[0]] = getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (getUserId())
            {
                ret[pMasqueradingVector[1]] = getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (getPreferenceId())
            {
                ret[pMasqueradingVector[2]] = getValueOfPreferenceId();
            }
            else
            {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (getName())
            {
                ret[pMasqueradingVector[3]] = getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (getStartPoint())
            {
                ret[pMasqueradingVector[4]] = getValueOfStartPoint();
            }
            else
            {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty())
        {
            if (getRouteLine())
            {
                ret[pMasqueradingVector[5]] = getValueOfRouteLine();
            }
            else
            {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[6].empty())
        {
            if (getDistanceKm())
            {
                ret[pMasqueradingVector[6]] = getValueOfDistanceKm();
            }
            else
            {
                ret[pMasqueradingVector[6]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[7].empty())
        {
            if (getMapSourceId())
            {
                ret[pMasqueradingVector[7]] = getValueOfMapSourceId();
            }
            else
            {
                ret[pMasqueradingVector[7]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[8].empty())
        {
            if (getCreatedAt())
            {
                ret[pMasqueradingVector[8]] = getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getUserId())
    {
        ret["user_id"] = getValueOfUserId();
    }
    else
    {
        ret["user_id"] = Json::Value();
    }
    if (getPreferenceId())
    {
        ret["preference_id"] = getValueOfPreferenceId();
    }
    else
    {
        ret["preference_id"] = Json::Value();
    }
    if (getName())
    {
        ret["name"] = getValueOfName();
    }
    else
    {
        ret["name"] = Json::Value();
    }
    if (getStartPoint())
    {
        ret["start_point"] = getValueOfStartPoint();
    }
    else
    {
        ret["start_point"] = Json::Value();
    }
    if (getRouteLine())
    {
        ret["route_line"] = getValueOfRouteLine();
    }
    else
    {
        ret["route_line"] = Json::Value();
    }
    if (getDistanceKm())
    {
        ret["distance_km"] = getValueOfDistanceKm();
    }
    else
    {
        ret["distance_km"] = Json::Value();
    }
    if (getMapSourceId())
    {
        ret["map_source_id"] = getValueOfMapSourceId();
    }
    else
    {
        ret["map_source_id"] = Json::Value();
    }
    if (getCreatedAt())
    {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

bool Routes::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if (pJson.isMember("user_id"))
    {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if (pJson.isMember("preference_id"))
    {
        if (!validJsonOfField(2, "preference_id", pJson["preference_id"], err, true))
            return false;
    }
    if (pJson.isMember("name"))
    {
        if (!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err = "The name column cannot be null";
        return false;
    }
    if (pJson.isMember("start_point"))
    {
        if (!validJsonOfField(4, "start_point", pJson["start_point"], err, true))
            return false;
    }
    else
    {
        err = "The start_point column cannot be null";
        return false;
    }
    if (pJson.isMember("route_line"))
    {
        if (!validJsonOfField(5, "route_line", pJson["route_line"], err, true))
            return false;
    }
    else
    {
        err = "The route_line column cannot be null";
        return false;
    }
    if (pJson.isMember("distance_km"))
    {
        if (!validJsonOfField(6, "distance_km", pJson["distance_km"], err, true))
            return false;
    }
    if (pJson.isMember("map_source_id"))
    {
        if (!validJsonOfField(7, "map_source_id", pJson["map_source_id"], err, true))
            return false;
    }
    if (pJson.isMember("created_at"))
    {
        if (!validJsonOfField(8, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Routes::validateMasqueradedJsonForCreation(const Json::Value&              pJson,
                                                const std::vector<std::string>& pMasqueradingVector,
                                                std::string&                    err)
{
    if (pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (pJson.isMember(pMasqueradingVector[0]))
            {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (pJson.isMember(pMasqueradingVector[1]))
            {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (pJson.isMember(pMasqueradingVector[2]))
            {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (pJson.isMember(pMasqueradingVector[3]))
            {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[3] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (pJson.isMember(pMasqueradingVector[4]))
            {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[4] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[5].empty())
        {
            if (pJson.isMember(pMasqueradingVector[5]))
            {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[5] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[6].empty())
        {
            if (pJson.isMember(pMasqueradingVector[6]))
            {
                if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[7].empty())
        {
            if (pJson.isMember(pMasqueradingVector[7]))
            {
                if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[8].empty())
        {
            if (pJson.isMember(pMasqueradingVector[8]))
            {
                if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err,
                                      true))
                    return false;
            }
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool Routes::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("user_id"))
    {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if (pJson.isMember("preference_id"))
    {
        if (!validJsonOfField(2, "preference_id", pJson["preference_id"], err, false))
            return false;
    }
    if (pJson.isMember("name"))
    {
        if (!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    if (pJson.isMember("start_point"))
    {
        if (!validJsonOfField(4, "start_point", pJson["start_point"], err, false))
            return false;
    }
    if (pJson.isMember("route_line"))
    {
        if (!validJsonOfField(5, "route_line", pJson["route_line"], err, false))
            return false;
    }
    if (pJson.isMember("distance_km"))
    {
        if (!validJsonOfField(6, "distance_km", pJson["distance_km"], err, false))
            return false;
    }
    if (pJson.isMember("map_source_id"))
    {
        if (!validJsonOfField(7, "map_source_id", pJson["map_source_id"], err, false))
            return false;
    }
    if (pJson.isMember("created_at"))
    {
        if (!validJsonOfField(8, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Routes::validateMasqueradedJsonForUpdate(const Json::Value&              pJson,
                                              const std::vector<std::string>& pMasqueradingVector,
                                              std::string&                    err)
{
    if (pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
        {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
        {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
        {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
        {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
        {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
        {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
        {
            if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
        {
            if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
        {
            if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err,
                                  false))
                return false;
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool Routes::validJsonOfField(size_t index, const std::string& fieldName, const Json::Value& pJson,
                              std::string& err, bool isForCreation)
{
    switch (index)
    {
        case 0:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (isForCreation)
            {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 100)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 100)";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 5:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 6:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 7:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 8:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
