/**
 *
 *  RoutePoi.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/RoutePoi.h"

#include <drogon/utils/Utilities.h>

#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smarttrails;

const std::string              RoutePoi::Cols::_route_id = "\"route_id\"";
const std::string              RoutePoi::Cols::_poi_id   = "\"poi_id\"";
const std::vector<std::string> RoutePoi::primaryKeyName  = {"route_id", "poi_id"};
const bool                     RoutePoi::hasPrimaryKey   = true;
const std::string              RoutePoi::tableName       = "\"route_poi\"";

const std::vector<typename RoutePoi::MetaData> RoutePoi::metaData_ = {
    {"route_id", "int32_t", "integer", 4, 0, 1, 1}, {"poi_id", "int32_t", "integer", 4, 0, 1, 1}};
const std::string& RoutePoi::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
RoutePoi::RoutePoi(const Row& r, const ssize_t indexOffset) noexcept
{
    if (indexOffset < 0)
    {
        if (!r["route_id"].isNull())
        {
            routeId_ = std::make_shared<int32_t>(r["route_id"].as<int32_t>());
        }
        if (!r["poi_id"].isNull())
        {
            poiId_ = std::make_shared<int32_t>(r["poi_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if (offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull())
        {
            routeId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull())
        {
            poiId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }
}

RoutePoi::RoutePoi(const Json::Value&              pJson,
                   const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            routeId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            poiId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

RoutePoi::RoutePoi(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("route_id"))
    {
        dirtyFlag_[0] = true;
        if (!pJson["route_id"].isNull())
        {
            routeId_ = std::make_shared<int32_t>((int32_t)pJson["route_id"].asInt64());
        }
    }
    if (pJson.isMember("poi_id"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["poi_id"].isNull())
        {
            poiId_ = std::make_shared<int32_t>((int32_t)pJson["poi_id"].asInt64());
        }
    }
}

void RoutePoi::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            routeId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            poiId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void RoutePoi::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("route_id"))
    {
        if (!pJson["route_id"].isNull())
        {
            routeId_ = std::make_shared<int32_t>((int32_t)pJson["route_id"].asInt64());
        }
    }
    if (pJson.isMember("poi_id"))
    {
        if (!pJson["poi_id"].isNull())
        {
            poiId_ = std::make_shared<int32_t>((int32_t)pJson["poi_id"].asInt64());
        }
    }
}

const int32_t& RoutePoi::getValueOfRouteId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (routeId_)
        return *routeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& RoutePoi::getRouteId() const noexcept
{
    return routeId_;
}
void RoutePoi::setRouteId(const int32_t& pRouteId) noexcept
{
    routeId_      = std::make_shared<int32_t>(pRouteId);
    dirtyFlag_[0] = true;
}

const int32_t& RoutePoi::getValueOfPoiId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (poiId_)
        return *poiId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& RoutePoi::getPoiId() const noexcept
{
    return poiId_;
}
void RoutePoi::setPoiId(const int32_t& pPoiId) noexcept
{
    poiId_        = std::make_shared<int32_t>(pPoiId);
    dirtyFlag_[1] = true;
}

void                              RoutePoi::updateId(const uint64_t id) {}
typename RoutePoi::PrimaryKeyType RoutePoi::getPrimaryKey() const
{
    return std::make_tuple(*routeId_, *poiId_);
}

const std::vector<std::string>& RoutePoi::insertColumns() noexcept
{
    static const std::vector<std::string> inCols = {"route_id", "poi_id"};
    return inCols;
}

void RoutePoi::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[0])
    {
        if (getRouteId())
        {
            binder << getValueOfRouteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1])
    {
        if (getPoiId())
        {
            binder << getValueOfPoiId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> RoutePoi::updateColumns() const
{
    std::vector<std::string> ret;
    if (dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void RoutePoi::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[0])
    {
        if (getRouteId())
        {
            binder << getValueOfRouteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1])
    {
        if (getPoiId())
        {
            binder << getValueOfPoiId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value RoutePoi::toJson() const
{
    Json::Value ret;
    if (getRouteId())
    {
        ret["route_id"] = getValueOfRouteId();
    }
    else
    {
        ret["route_id"] = Json::Value();
    }
    if (getPoiId())
    {
        ret["poi_id"] = getValueOfPoiId();
    }
    else
    {
        ret["poi_id"] = Json::Value();
    }
    return ret;
}

std::string RoutePoi::toString() const
{
    return toJson().toStyledString();
}

Json::Value RoutePoi::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if (pMasqueradingVector.size() == 2)
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (getRouteId())
            {
                ret[pMasqueradingVector[0]] = getValueOfRouteId();
            }
            else
            {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (getPoiId())
            {
                ret[pMasqueradingVector[1]] = getValueOfPoiId();
            }
            else
            {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getRouteId())
    {
        ret["route_id"] = getValueOfRouteId();
    }
    else
    {
        ret["route_id"] = Json::Value();
    }
    if (getPoiId())
    {
        ret["poi_id"] = getValueOfPoiId();
    }
    else
    {
        ret["poi_id"] = Json::Value();
    }
    return ret;
}

bool RoutePoi::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("route_id"))
    {
        if (!validJsonOfField(0, "route_id", pJson["route_id"], err, true))
            return false;
    }
    else
    {
        err = "The route_id column cannot be null";
        return false;
    }
    if (pJson.isMember("poi_id"))
    {
        if (!validJsonOfField(1, "poi_id", pJson["poi_id"], err, true))
            return false;
    }
    else
    {
        err = "The poi_id column cannot be null";
        return false;
    }
    return true;
}
bool RoutePoi::validateMasqueradedJsonForCreation(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err)
{
    if (pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (pJson.isMember(pMasqueradingVector[0]))
            {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (pJson.isMember(pMasqueradingVector[1]))
            {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool RoutePoi::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("route_id"))
    {
        if (!validJsonOfField(0, "route_id", pJson["route_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("poi_id"))
    {
        if (!validJsonOfField(1, "poi_id", pJson["poi_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool RoutePoi::validateMasqueradedJsonForUpdate(const Json::Value&              pJson,
                                                const std::vector<std::string>& pMasqueradingVector,
                                                std::string&                    err)
{
    if (pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
        {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
        {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool RoutePoi::validJsonOfField(size_t index, const std::string& fieldName,
                                const Json::Value& pJson, std::string& err, bool isForCreation)
{
    switch (index)
    {
        case 0:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
