/**
 *
 *  SpatialRefSys.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/SpatialRefSys.h"

#include <drogon/utils/Utilities.h>

#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smarttrails;

const std::string SpatialRefSys::Cols::_srid      = "\"srid\"";
const std::string SpatialRefSys::Cols::_auth_name = "\"auth_name\"";
const std::string SpatialRefSys::Cols::_auth_srid = "\"auth_srid\"";
const std::string SpatialRefSys::Cols::_srtext    = "\"srtext\"";
const std::string SpatialRefSys::Cols::_proj4text = "\"proj4text\"";
const std::string SpatialRefSys::primaryKeyName   = "srid";
const bool        SpatialRefSys::hasPrimaryKey    = true;
const std::string SpatialRefSys::tableName        = "\"spatial_ref_sys\"";

const std::vector<typename SpatialRefSys::MetaData> SpatialRefSys::metaData_ = {
    {"srid", "int32_t", "integer", 4, 0, 1, 1},
    {"auth_name", "std::string", "character varying", 256, 0, 0, 0},
    {"auth_srid", "int32_t", "integer", 4, 0, 0, 0},
    {"srtext", "std::string", "character varying", 2048, 0, 0, 0},
    {"proj4text", "std::string", "character varying", 2048, 0, 0, 0}};
const std::string& SpatialRefSys::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SpatialRefSys::SpatialRefSys(const Row& r, const ssize_t indexOffset) noexcept
{
    if (indexOffset < 0)
    {
        if (!r["srid"].isNull())
        {
            srid_ = std::make_shared<int32_t>(r["srid"].as<int32_t>());
        }
        if (!r["auth_name"].isNull())
        {
            authName_ = std::make_shared<std::string>(r["auth_name"].as<std::string>());
        }
        if (!r["auth_srid"].isNull())
        {
            authSrid_ = std::make_shared<int32_t>(r["auth_srid"].as<int32_t>());
        }
        if (!r["srtext"].isNull())
        {
            srtext_ = std::make_shared<std::string>(r["srtext"].as<std::string>());
        }
        if (!r["proj4text"].isNull())
        {
            proj4text_ = std::make_shared<std::string>(r["proj4text"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if (offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull())
        {
            srid_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull())
        {
            authName_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if (!r[index].isNull())
        {
            authSrid_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if (!r[index].isNull())
        {
            srtext_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if (!r[index].isNull())
        {
            proj4text_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
    }
}

SpatialRefSys::SpatialRefSys(const Json::Value&              pJson,
                             const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            srid_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            authName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            authSrid_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            srtext_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            proj4text_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

SpatialRefSys::SpatialRefSys(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("srid"))
    {
        dirtyFlag_[0] = true;
        if (!pJson["srid"].isNull())
        {
            srid_ = std::make_shared<int32_t>((int32_t)pJson["srid"].asInt64());
        }
    }
    if (pJson.isMember("auth_name"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["auth_name"].isNull())
        {
            authName_ = std::make_shared<std::string>(pJson["auth_name"].asString());
        }
    }
    if (pJson.isMember("auth_srid"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["auth_srid"].isNull())
        {
            authSrid_ = std::make_shared<int32_t>((int32_t)pJson["auth_srid"].asInt64());
        }
    }
    if (pJson.isMember("srtext"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["srtext"].isNull())
        {
            srtext_ = std::make_shared<std::string>(pJson["srtext"].asString());
        }
    }
    if (pJson.isMember("proj4text"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["proj4text"].isNull())
        {
            proj4text_ = std::make_shared<std::string>(pJson["proj4text"].asString());
        }
    }
}

void SpatialRefSys::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            srid_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            authName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            authSrid_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            srtext_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            proj4text_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void SpatialRefSys::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("srid"))
    {
        if (!pJson["srid"].isNull())
        {
            srid_ = std::make_shared<int32_t>((int32_t)pJson["srid"].asInt64());
        }
    }
    if (pJson.isMember("auth_name"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["auth_name"].isNull())
        {
            authName_ = std::make_shared<std::string>(pJson["auth_name"].asString());
        }
    }
    if (pJson.isMember("auth_srid"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["auth_srid"].isNull())
        {
            authSrid_ = std::make_shared<int32_t>((int32_t)pJson["auth_srid"].asInt64());
        }
    }
    if (pJson.isMember("srtext"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["srtext"].isNull())
        {
            srtext_ = std::make_shared<std::string>(pJson["srtext"].asString());
        }
    }
    if (pJson.isMember("proj4text"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["proj4text"].isNull())
        {
            proj4text_ = std::make_shared<std::string>(pJson["proj4text"].asString());
        }
    }
}

const int32_t& SpatialRefSys::getValueOfSrid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (srid_)
        return *srid_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& SpatialRefSys::getSrid() const noexcept
{
    return srid_;
}
void SpatialRefSys::setSrid(const int32_t& pSrid) noexcept
{
    srid_         = std::make_shared<int32_t>(pSrid);
    dirtyFlag_[0] = true;
}
const typename SpatialRefSys::PrimaryKeyType& SpatialRefSys::getPrimaryKey() const
{
    assert(srid_);
    return *srid_;
}

const std::string& SpatialRefSys::getValueOfAuthName() const noexcept
{
    static const std::string defaultValue = std::string();
    if (authName_)
        return *authName_;
    return defaultValue;
}
const std::shared_ptr<std::string>& SpatialRefSys::getAuthName() const noexcept
{
    return authName_;
}
void SpatialRefSys::setAuthName(const std::string& pAuthName) noexcept
{
    authName_     = std::make_shared<std::string>(pAuthName);
    dirtyFlag_[1] = true;
}
void SpatialRefSys::setAuthName(std::string&& pAuthName) noexcept
{
    authName_     = std::make_shared<std::string>(std::move(pAuthName));
    dirtyFlag_[1] = true;
}
void SpatialRefSys::setAuthNameToNull() noexcept
{
    authName_.reset();
    dirtyFlag_[1] = true;
}

const int32_t& SpatialRefSys::getValueOfAuthSrid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (authSrid_)
        return *authSrid_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& SpatialRefSys::getAuthSrid() const noexcept
{
    return authSrid_;
}
void SpatialRefSys::setAuthSrid(const int32_t& pAuthSrid) noexcept
{
    authSrid_     = std::make_shared<int32_t>(pAuthSrid);
    dirtyFlag_[2] = true;
}
void SpatialRefSys::setAuthSridToNull() noexcept
{
    authSrid_.reset();
    dirtyFlag_[2] = true;
}

const std::string& SpatialRefSys::getValueOfSrtext() const noexcept
{
    static const std::string defaultValue = std::string();
    if (srtext_)
        return *srtext_;
    return defaultValue;
}
const std::shared_ptr<std::string>& SpatialRefSys::getSrtext() const noexcept
{
    return srtext_;
}
void SpatialRefSys::setSrtext(const std::string& pSrtext) noexcept
{
    srtext_       = std::make_shared<std::string>(pSrtext);
    dirtyFlag_[3] = true;
}
void SpatialRefSys::setSrtext(std::string&& pSrtext) noexcept
{
    srtext_       = std::make_shared<std::string>(std::move(pSrtext));
    dirtyFlag_[3] = true;
}
void SpatialRefSys::setSrtextToNull() noexcept
{
    srtext_.reset();
    dirtyFlag_[3] = true;
}

const std::string& SpatialRefSys::getValueOfProj4text() const noexcept
{
    static const std::string defaultValue = std::string();
    if (proj4text_)
        return *proj4text_;
    return defaultValue;
}
const std::shared_ptr<std::string>& SpatialRefSys::getProj4text() const noexcept
{
    return proj4text_;
}
void SpatialRefSys::setProj4text(const std::string& pProj4text) noexcept
{
    proj4text_    = std::make_shared<std::string>(pProj4text);
    dirtyFlag_[4] = true;
}
void SpatialRefSys::setProj4text(std::string&& pProj4text) noexcept
{
    proj4text_    = std::make_shared<std::string>(std::move(pProj4text));
    dirtyFlag_[4] = true;
}
void SpatialRefSys::setProj4textToNull() noexcept
{
    proj4text_.reset();
    dirtyFlag_[4] = true;
}

void SpatialRefSys::updateId(const uint64_t id) {}

const std::vector<std::string>& SpatialRefSys::insertColumns() noexcept
{
    static const std::vector<std::string> inCols = {"srid", "auth_name", "auth_srid", "srtext",
                                                    "proj4text"};
    return inCols;
}

void SpatialRefSys::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[0])
    {
        if (getSrid())
        {
            binder << getValueOfSrid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1])
    {
        if (getAuthName())
        {
            binder << getValueOfAuthName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getAuthSrid())
        {
            binder << getValueOfAuthSrid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getSrtext())
        {
            binder << getValueOfSrtext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getProj4text())
        {
            binder << getValueOfProj4text();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SpatialRefSys::updateColumns() const
{
    std::vector<std::string> ret;
    if (dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void SpatialRefSys::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[0])
    {
        if (getSrid())
        {
            binder << getValueOfSrid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1])
    {
        if (getAuthName())
        {
            binder << getValueOfAuthName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getAuthSrid())
        {
            binder << getValueOfAuthSrid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getSrtext())
        {
            binder << getValueOfSrtext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getProj4text())
        {
            binder << getValueOfProj4text();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SpatialRefSys::toJson() const
{
    Json::Value ret;
    if (getSrid())
    {
        ret["srid"] = getValueOfSrid();
    }
    else
    {
        ret["srid"] = Json::Value();
    }
    if (getAuthName())
    {
        ret["auth_name"] = getValueOfAuthName();
    }
    else
    {
        ret["auth_name"] = Json::Value();
    }
    if (getAuthSrid())
    {
        ret["auth_srid"] = getValueOfAuthSrid();
    }
    else
    {
        ret["auth_srid"] = Json::Value();
    }
    if (getSrtext())
    {
        ret["srtext"] = getValueOfSrtext();
    }
    else
    {
        ret["srtext"] = Json::Value();
    }
    if (getProj4text())
    {
        ret["proj4text"] = getValueOfProj4text();
    }
    else
    {
        ret["proj4text"] = Json::Value();
    }
    return ret;
}

std::string SpatialRefSys::toString() const
{
    return toJson().toStyledString();
}

Json::Value
SpatialRefSys::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if (pMasqueradingVector.size() == 5)
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (getSrid())
            {
                ret[pMasqueradingVector[0]] = getValueOfSrid();
            }
            else
            {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (getAuthName())
            {
                ret[pMasqueradingVector[1]] = getValueOfAuthName();
            }
            else
            {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (getAuthSrid())
            {
                ret[pMasqueradingVector[2]] = getValueOfAuthSrid();
            }
            else
            {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (getSrtext())
            {
                ret[pMasqueradingVector[3]] = getValueOfSrtext();
            }
            else
            {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (getProj4text())
            {
                ret[pMasqueradingVector[4]] = getValueOfProj4text();
            }
            else
            {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getSrid())
    {
        ret["srid"] = getValueOfSrid();
    }
    else
    {
        ret["srid"] = Json::Value();
    }
    if (getAuthName())
    {
        ret["auth_name"] = getValueOfAuthName();
    }
    else
    {
        ret["auth_name"] = Json::Value();
    }
    if (getAuthSrid())
    {
        ret["auth_srid"] = getValueOfAuthSrid();
    }
    else
    {
        ret["auth_srid"] = Json::Value();
    }
    if (getSrtext())
    {
        ret["srtext"] = getValueOfSrtext();
    }
    else
    {
        ret["srtext"] = Json::Value();
    }
    if (getProj4text())
    {
        ret["proj4text"] = getValueOfProj4text();
    }
    else
    {
        ret["proj4text"] = Json::Value();
    }
    return ret;
}

bool SpatialRefSys::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("srid"))
    {
        if (!validJsonOfField(0, "srid", pJson["srid"], err, true))
            return false;
    }
    else
    {
        err = "The srid column cannot be null";
        return false;
    }
    if (pJson.isMember("auth_name"))
    {
        if (!validJsonOfField(1, "auth_name", pJson["auth_name"], err, true))
            return false;
    }
    if (pJson.isMember("auth_srid"))
    {
        if (!validJsonOfField(2, "auth_srid", pJson["auth_srid"], err, true))
            return false;
    }
    if (pJson.isMember("srtext"))
    {
        if (!validJsonOfField(3, "srtext", pJson["srtext"], err, true))
            return false;
    }
    if (pJson.isMember("proj4text"))
    {
        if (!validJsonOfField(4, "proj4text", pJson["proj4text"], err, true))
            return false;
    }
    return true;
}
bool SpatialRefSys::validateMasqueradedJsonForCreation(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err)
{
    if (pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (pJson.isMember(pMasqueradingVector[0]))
            {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
            else
            {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (pJson.isMember(pMasqueradingVector[1]))
            {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (pJson.isMember(pMasqueradingVector[2]))
            {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (pJson.isMember(pMasqueradingVector[3]))
            {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (pJson.isMember(pMasqueradingVector[4]))
            {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                      true))
                    return false;
            }
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool SpatialRefSys::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("srid"))
    {
        if (!validJsonOfField(0, "srid", pJson["srid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("auth_name"))
    {
        if (!validJsonOfField(1, "auth_name", pJson["auth_name"], err, false))
            return false;
    }
    if (pJson.isMember("auth_srid"))
    {
        if (!validJsonOfField(2, "auth_srid", pJson["auth_srid"], err, false))
            return false;
    }
    if (pJson.isMember("srtext"))
    {
        if (!validJsonOfField(3, "srtext", pJson["srtext"], err, false))
            return false;
    }
    if (pJson.isMember("proj4text"))
    {
        if (!validJsonOfField(4, "proj4text", pJson["proj4text"], err, false))
            return false;
    }
    return true;
}
bool SpatialRefSys::validateMasqueradedJsonForUpdate(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err)
{
    if (pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
        {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
        {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
        {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
        {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
        {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                  false))
                return false;
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool SpatialRefSys::validJsonOfField(size_t index, const std::string& fieldName,
                                     const Json::Value& pJson, std::string& err, bool isForCreation)
{
    switch (index)
    {
        case 0:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 256)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 256)";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 2048)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 2048)";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() &&
                std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                        .from_bytes(pJson.asCString())
                        .size() > 2048)
            {
                err = "String length exceeds limit for the " + fieldName +
                      " field (the maximum value is 2048)";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
