/**
 *
 *  UserPreferences.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/UserPreferences.h"

#include <drogon/utils/Utilities.h>

#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smarttrails;

const std::string UserPreferences::Cols::_id                    = "\"id\"";
const std::string UserPreferences::Cols::_user_id               = "\"user_id\"";
const std::string UserPreferences::Cols::_preferred_distance_km = "\"preferred_distance_km\"";
const std::string UserPreferences::Cols::_poi_type_ids          = "\"poi_type_ids\"";
const std::string UserPreferences::Cols::_updated_at            = "\"updated_at\"";
const std::string UserPreferences::primaryKeyName               = "id";
const bool        UserPreferences::hasPrimaryKey                = true;
const std::string UserPreferences::tableName                    = "\"user_preferences\"";

const std::vector<typename UserPreferences::MetaData> UserPreferences::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"user_id", "int32_t", "integer", 4, 0, 0, 0},
    {"preferred_distance_km", "std::string", "numeric", 0, 0, 0, 0},
    {"poi_type_ids", "std::string", "ARRAY", 0, 0, 0, 0},
    {"updated_at", "::trantor::Date", "timestamp with time zone", 0, 0, 0, 0}};
const std::string& UserPreferences::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserPreferences::UserPreferences(const Row& r, const ssize_t indexOffset) noexcept
{
    if (indexOffset < 0)
    {
        if (!r["id"].isNull())
        {
            id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if (!r["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if (!r["preferred_distance_km"].isNull())
        {
            preferredDistanceKm_ =
                std::make_shared<std::string>(r["preferred_distance_km"].as<std::string>());
        }
        if (!r["poi_type_ids"].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(r["poi_type_ids"].as<std::string>());
        }
        if (!r["updated_at"].isNull())
        {
            auto      timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if (offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull())
        {
            id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull())
        {
            userId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if (!r[index].isNull())
        {
            preferredDistanceKm_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if (!r[index].isNull())
        {
            auto      timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

UserPreferences::UserPreferences(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            preferredDistanceKm_ =
                std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

UserPreferences::UserPreferences(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if (pJson.isMember("preferred_distance_km"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["preferred_distance_km"].isNull())
        {
            preferredDistanceKm_ =
                std::make_shared<std::string>(pJson["preferred_distance_km"].asString());
        }
    }
    if (pJson.isMember("poi_type_ids"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["poi_type_ids"].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(pJson["poi_type_ids"].asString());
        }
    }
    if (pJson.isMember("updated_at"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["updated_at"].isNull())
        {
            auto      timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void UserPreferences::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if (pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if (!pJson[pMasqueradingVector[0]].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull())
        {
            preferredDistanceKm_ =
                std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull())
        {
            auto      timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void UserPreferences::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if (pJson.isMember("id"))
    {
        if (!pJson["id"].isNull())
        {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull())
        {
            userId_ = std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if (pJson.isMember("preferred_distance_km"))
    {
        dirtyFlag_[2] = true;
        if (!pJson["preferred_distance_km"].isNull())
        {
            preferredDistanceKm_ =
                std::make_shared<std::string>(pJson["preferred_distance_km"].asString());
        }
    }
    if (pJson.isMember("poi_type_ids"))
    {
        dirtyFlag_[3] = true;
        if (!pJson["poi_type_ids"].isNull())
        {
            poiTypeIds_ = std::make_shared<std::string>(pJson["poi_type_ids"].asString());
        }
    }
    if (pJson.isMember("updated_at"))
    {
        dirtyFlag_[4] = true;
        if (!pJson["updated_at"].isNull())
        {
            auto      timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto   p          = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t          = mktime(&stm);
            size_t decimalNum = 0;
            if (p)
            {
                if (*p == '.')
                {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

const int32_t& UserPreferences::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& UserPreferences::getId() const noexcept
{
    return id_;
}
void UserPreferences::setId(const int32_t& pId) noexcept
{
    id_           = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename UserPreferences::PrimaryKeyType& UserPreferences::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t& UserPreferences::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if (userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t>& UserPreferences::getUserId() const noexcept
{
    return userId_;
}
void UserPreferences::setUserId(const int32_t& pUserId) noexcept
{
    userId_       = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}
void UserPreferences::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[1] = true;
}

const std::string& UserPreferences::getValueOfPreferredDistanceKm() const noexcept
{
    static const std::string defaultValue = std::string();
    if (preferredDistanceKm_)
        return *preferredDistanceKm_;
    return defaultValue;
}
const std::shared_ptr<std::string>& UserPreferences::getPreferredDistanceKm() const noexcept
{
    return preferredDistanceKm_;
}
void UserPreferences::setPreferredDistanceKm(const std::string& pPreferredDistanceKm) noexcept
{
    preferredDistanceKm_ = std::make_shared<std::string>(pPreferredDistanceKm);
    dirtyFlag_[2]        = true;
}
void UserPreferences::setPreferredDistanceKm(std::string&& pPreferredDistanceKm) noexcept
{
    preferredDistanceKm_ = std::make_shared<std::string>(std::move(pPreferredDistanceKm));
    dirtyFlag_[2]        = true;
}
void UserPreferences::setPreferredDistanceKmToNull() noexcept
{
    preferredDistanceKm_.reset();
    dirtyFlag_[2] = true;
}

const std::string& UserPreferences::getValueOfPoiTypeIds() const noexcept
{
    static const std::string defaultValue = std::string();
    if (poiTypeIds_)
        return *poiTypeIds_;
    return defaultValue;
}
const std::shared_ptr<std::string>& UserPreferences::getPoiTypeIds() const noexcept
{
    return poiTypeIds_;
}
void UserPreferences::setPoiTypeIds(const std::string& pPoiTypeIds) noexcept
{
    poiTypeIds_   = std::make_shared<std::string>(pPoiTypeIds);
    dirtyFlag_[3] = true;
}
void UserPreferences::setPoiTypeIds(std::string&& pPoiTypeIds) noexcept
{
    poiTypeIds_   = std::make_shared<std::string>(std::move(pPoiTypeIds));
    dirtyFlag_[3] = true;
}
void UserPreferences::setPoiTypeIdsToNull() noexcept
{
    poiTypeIds_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date& UserPreferences::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date>& UserPreferences::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void UserPreferences::setUpdatedAt(const ::trantor::Date& pUpdatedAt) noexcept
{
    updatedAt_    = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[4] = true;
}
void UserPreferences::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[4] = true;
}

void UserPreferences::updateId(const uint64_t id) {}

const std::vector<std::string>& UserPreferences::insertColumns() noexcept
{
    static const std::vector<std::string> inCols = {"user_id", "preferred_distance_km",
                                                    "poi_type_ids", "updated_at"};
    return inCols;
}

void UserPreferences::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getPreferredDistanceKm())
        {
            binder << getValueOfPreferredDistanceKm();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getPoiTypeIds())
        {
            binder << getValueOfPoiTypeIds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserPreferences::updateColumns() const
{
    std::vector<std::string> ret;
    if (dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void UserPreferences::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if (dirtyFlag_[1])
    {
        if (getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2])
    {
        if (getPreferredDistanceKm())
        {
            binder << getValueOfPreferredDistanceKm();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3])
    {
        if (getPoiTypeIds())
        {
            binder << getValueOfPoiTypeIds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4])
    {
        if (getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserPreferences::toJson() const
{
    Json::Value ret;
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getUserId())
    {
        ret["user_id"] = getValueOfUserId();
    }
    else
    {
        ret["user_id"] = Json::Value();
    }
    if (getPreferredDistanceKm())
    {
        ret["preferred_distance_km"] = getValueOfPreferredDistanceKm();
    }
    else
    {
        ret["preferred_distance_km"] = Json::Value();
    }
    if (getPoiTypeIds())
    {
        ret["poi_type_ids"] = getValueOfPoiTypeIds();
    }
    else
    {
        ret["poi_type_ids"] = Json::Value();
    }
    if (getUpdatedAt())
    {
        ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"] = Json::Value();
    }
    return ret;
}

std::string UserPreferences::toString() const
{
    return toJson().toStyledString();
}

Json::Value
UserPreferences::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if (pMasqueradingVector.size() == 5)
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (getId())
            {
                ret[pMasqueradingVector[0]] = getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (getUserId())
            {
                ret[pMasqueradingVector[1]] = getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (getPreferredDistanceKm())
            {
                ret[pMasqueradingVector[2]] = getValueOfPreferredDistanceKm();
            }
            else
            {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (getPoiTypeIds())
            {
                ret[pMasqueradingVector[3]] = getValueOfPoiTypeIds();
            }
            else
            {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (getUpdatedAt())
            {
                ret[pMasqueradingVector[4]] = getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId())
    {
        ret["id"] = getValueOfId();
    }
    else
    {
        ret["id"] = Json::Value();
    }
    if (getUserId())
    {
        ret["user_id"] = getValueOfUserId();
    }
    else
    {
        ret["user_id"] = Json::Value();
    }
    if (getPreferredDistanceKm())
    {
        ret["preferred_distance_km"] = getValueOfPreferredDistanceKm();
    }
    else
    {
        ret["preferred_distance_km"] = Json::Value();
    }
    if (getPoiTypeIds())
    {
        ret["poi_type_ids"] = getValueOfPoiTypeIds();
    }
    else
    {
        ret["poi_type_ids"] = Json::Value();
    }
    if (getUpdatedAt())
    {
        ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"] = Json::Value();
    }
    return ret;
}

bool UserPreferences::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if (pJson.isMember("user_id"))
    {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if (pJson.isMember("preferred_distance_km"))
    {
        if (!validJsonOfField(2, "preferred_distance_km", pJson["preferred_distance_km"], err,
                              true))
            return false;
    }
    if (pJson.isMember("poi_type_ids"))
    {
        if (!validJsonOfField(3, "poi_type_ids", pJson["poi_type_ids"], err, true))
            return false;
    }
    if (pJson.isMember("updated_at"))
    {
        if (!validJsonOfField(4, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool UserPreferences::validateMasqueradedJsonForCreation(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err)
{
    if (pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty())
        {
            if (pJson.isMember(pMasqueradingVector[0]))
            {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[1].empty())
        {
            if (pJson.isMember(pMasqueradingVector[1]))
            {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[2].empty())
        {
            if (pJson.isMember(pMasqueradingVector[2]))
            {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty())
        {
            if (pJson.isMember(pMasqueradingVector[3]))
            {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty())
        {
            if (pJson.isMember(pMasqueradingVector[4]))
            {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                      true))
                    return false;
            }
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool UserPreferences::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if (pJson.isMember("id"))
    {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("user_id"))
    {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if (pJson.isMember("preferred_distance_km"))
    {
        if (!validJsonOfField(2, "preferred_distance_km", pJson["preferred_distance_km"], err,
                              false))
            return false;
    }
    if (pJson.isMember("poi_type_ids"))
    {
        if (!validJsonOfField(3, "poi_type_ids", pJson["poi_type_ids"], err, false))
            return false;
    }
    if (pJson.isMember("updated_at"))
    {
        if (!validJsonOfField(4, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool UserPreferences::validateMasqueradedJsonForUpdate(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err)
{
    if (pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try
    {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
        {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        }
        else
        {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
        {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
        {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
        {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
        {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err,
                                  false))
                return false;
        }
    }
    catch (const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}
bool UserPreferences::validJsonOfField(size_t index, const std::string& fieldName,
                                       const Json::Value& pJson, std::string& err,
                                       bool isForCreation)
{
    switch (index)
    {
        case 0:
            if (pJson.isNull())
            {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (isForCreation)
            {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isInt())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull())
            {
                return true;
            }
            if (!pJson.isString())
            {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
